/**
 * Chest X-ray AI Analysis – React app with API connections
 *
 * This matches the layout created by the Figma plugin (figma-plugin-chest-xray).
 * Connections: Upload → POST /analyze → modelOutput (labels + llm).
 *
 * Usage:
 *   1. Point VITE_API_URL (or default http://localhost:8000) at your backend.
 *   2. Run backend: python -m uvicorn api.app:app --reload --port 8000
 *   3. Run this app (e.g. npm run dev).
 */

import { useState } from "react";

type AppState = "empty" | "loading" | "results";
type Status = "present" | "uncertain" | "not-present";

interface Label {
  label: string;
  probability: number;
  status: Status;
}

interface RankedFinding {
  label: string;
  status: Status;
  probability: number;
  rationale: string;
}

interface Differential {
  condition: string;
  confidence: "low" | "medium" | "high";
  reason: string;
}

interface RecommendedAction {
  action: string;
  urgency: "routine" | "soon" | "urgent";
}

interface ModelOutput {
  labels: Label[];
  llm: {
    summary: string;
    rankedFindings: RankedFinding[];
    differentials: Differential[];
    recommendedActions: RecommendedAction[];
    safetyNote: string;
  };
}

const API_URL = import.meta.env?.VITE_API_URL ?? "http://localhost:8000";

const MOCK_OUTPUT: ModelOutput = {
  labels: [
    { label: "Pleural Effusion", probability: 0.92, status: "present" },
    { label: "Cardiomegaly", probability: 0.78, status: "present" },
    { label: "Edema", probability: 0.65, status: "uncertain" },
    { label: "Consolidation", probability: 0.54, status: "uncertain" },
    { label: "Atelectasis", probability: 0.42, status: "uncertain" },
    { label: "Pneumothorax", probability: 0.15, status: "not-present" },
    { label: "Lung Opacity", probability: 0.71, status: "present" },
    { label: "Lung Lesion", probability: 0.12, status: "not-present" },
    { label: "Fracture", probability: 0.08, status: "not-present" },
    { label: "Support Devices", probability: 0.03, status: "not-present" },
    { label: "Pneumonia", probability: 0.48, status: "uncertain" },
    { label: "No Finding", probability: 0.05, status: "not-present" },
    { label: "Enlarged Cardiomediastinum", probability: 0.68, status: "uncertain" },
    { label: "Pleural Other", probability: 0.23, status: "not-present" },
  ],
  llm: {
    summary:
      "The chest X-ray demonstrates findings consistent with moderate pleural effusion and cardiomegaly. This analysis is for research/education only.",
    rankedFindings: [
      { label: "Pleural Effusion", status: "present", probability: 0.92, rationale: "High probability from model output." },
      { label: "Cardiomegaly", status: "present", probability: 0.78, rationale: "Enlarged cardiac silhouette suggested by model." },
    ],
    differentials: [
      { condition: "Clinical correlation recommended", confidence: "medium", reason: "Based on model outputs." },
    ],
    recommendedActions: [
      { action: "Compare with prior imaging if available", urgency: "soon" },
      { action: "Obtain formal radiologist interpretation", urgency: "soon" },
    ],
    safetyNote: "This analysis is generated by AI for educational and research purposes only. Not medical advice.",
  },
};

function App() {
  const [appState, setAppState] = useState<AppState>("empty");
  const [imageUrl, setImageUrl] = useState<string>("");
  const [modelOutput, setModelOutput] = useState<ModelOutput | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [filterMode, setFilterMode] = useState<"all" | "relevant">("all");

  const handleFileSelect = async (file: File) => {
    const url = URL.createObjectURL(file);
    setImageUrl(url);
    setAppState("loading");
    setError(null);

    try {
      const formData = new FormData();
      formData.append("file", file);

      const res = await fetch(`${API_URL}/analyze`, {
        method: "POST",
        body: formData,
      });

      if (!res.ok) {
        const errText = await res.text();
        throw new Error(errText || `Analysis failed: ${res.status}`);
      }

      const data: ModelOutput = await res.json();
      setModelOutput(data);
      setAppState("results");
    } catch (e) {
      console.error(e);
      setError(e instanceof Error ? e.message : "Analysis failed");
      setAppState("empty");
      setImageUrl("");
    }
  };

  const handleReset = () => {
    setAppState("empty");
    setImageUrl("");
    setFilterMode("all");
    setModelOutput(null);
    setError(null);
  };

  const output: ModelOutput = modelOutput ?? MOCK_OUTPUT;
  const filteredLabels =
    filterMode === "relevant"
      ? output.labels.filter((l) => l.status !== "not-present")
      : output.labels;
  const sortedLabels = [...filteredLabels].sort((a, b) => b.probability - a.probability);

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white border-b shadow-sm">
        <div className="max-w-[1440px] mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold">Chest X-ray AI Analysis</h1>
              <p className="text-sm text-gray-600 mt-1">
                Vision Model + LLM Explanation Pipeline • Connected to {API_URL}
              </p>
            </div>
            <div className="flex items-center gap-3">
              {appState === "results" && (
                <>
                  <button className="px-3 py-1.5 border rounded text-sm">Export Report</button>
                  <button className="px-3 py-1.5 border rounded text-sm" onClick={handleReset}>
                    New Analysis
                  </button>
                </>
              )}
            </div>
          </div>
        </div>
      </header>

      <div className="max-w-[1440px] mx-auto p-6">
        {error && (
          <div className="mb-4 p-4 bg-red-50 border border-red-200 text-red-800 rounded">
            {error}
          </div>
        )}

        <div className="grid grid-cols-3 gap-6">
          {/* Left: Image */}
          <div className="space-y-4">
            {appState === "empty" && (
              <>
                <div
                  className="border-2 border-dashed border-gray-300 rounded-lg p-12 text-center bg-gray-50 cursor-pointer hover:bg-gray-100"
                  onClick={() => document.getElementById("file-input")?.click()}
                >
                  <input
                    id="file-input"
                    type="file"
                    accept="image/*"
                    className="hidden"
                    onChange={(e) => {
                      const f = e.target.files?.[0];
                      if (f) handleFileSelect(f);
                    }}
                  />
                  <p className="text-gray-600">Drop X-ray or click to upload → POST /analyze</p>
                </div>
                <div className="bg-gray-100 rounded-lg p-12">
                  <p className="text-center text-gray-500">Upload an X-ray to see the analysis</p>
                </div>
              </>
            )}

            {(appState === "loading" || appState === "results") && (
              <>
                <div className="flex items-center justify-between">
                  <h2 className="text-lg font-semibold">X-ray Viewer</h2>
                  <button className="text-sm text-gray-600 hover:underline" onClick={handleReset}>
                    Upload New
                  </button>
                </div>
                <div className="bg-white rounded-lg border shadow-sm overflow-hidden">
                  {imageUrl && (
                    <img src={imageUrl} alt="X-ray" className="w-full h-auto max-h-[400px] object-contain" />
                  )}
                </div>
              </>
            )}
          </div>

          {/* Middle: Model Predictions ← response.labels */}
          <div className="space-y-4">
            <div className="bg-white rounded-lg border shadow-sm p-4">
              <div className="flex items-center justify-between mb-3">
                <div>
                  <h2 className="text-lg font-semibold">Model Predictions</h2>
                  <p className="text-sm text-gray-500">CheXpert 14-label probabilities ← response.labels</p>
                </div>
                {appState === "results" && (
                  <button
                    className="text-sm border px-2 py-1 rounded"
                    onClick={() => setFilterMode(filterMode === "all" ? "relevant" : "all")}
                  >
                    {filterMode === "all" ? "Show Relevant" : "Show All"}
                  </button>
                )}
              </div>
              <div className="space-y-2">
                {appState === "empty" && (
                  <p className="text-sm text-gray-500 text-center py-8">Upload an X-ray to see model predictions</p>
                )}
                {appState === "loading" && (
                  <p className="text-sm text-gray-600">Computing label probabilities...</p>
                )}
                {appState === "results" &&
                  sortedLabels.map((item, idx) => (
                    <div key={idx} className="flex items-center justify-between py-1 border-b border-gray-100">
                      <span className="text-sm">{item.label}</span>
                      <span className="text-sm text-gray-600">{(item.probability * 100).toFixed(1)}%</span>
                      <span
                        className={`text-xs px-2 py-0.5 rounded ${
                          item.status === "present"
                            ? "bg-green-100 text-green-800"
                            : item.status === "uncertain"
                            ? "bg-amber-100 text-amber-800"
                            : "bg-gray-100 text-gray-600"
                        }`}
                      >
                        {item.status}
                      </span>
                    </div>
                  ))}
              </div>
            </div>
          </div>

          {/* Right: LLM ← response.llm */}
          <div className="space-y-4">
            {appState === "empty" && (
              <div className="bg-gray-100 rounded-lg p-12">
                <p className="text-center text-gray-500">AI-generated findings will appear here</p>
              </div>
            )}

            {appState === "loading" && (
              <div className="bg-white rounded-lg border p-4">
                <h2 className="font-semibold mb-2">AI Findings Summary</h2>
                <p className="text-sm text-gray-600">Generating explanation...</p>
              </div>
            )}

            {appState === "results" && (
              <div className="space-y-4">
                <div className="bg-white rounded-lg border shadow-sm p-4">
                  <h2 className="font-semibold mb-1">AI Findings Summary</h2>
                  <p className="text-xs text-gray-500 mb-2">← response.llm.summary</p>
                  <p className="text-sm leading-relaxed">{output.llm.summary}</p>
                </div>

                <div className="bg-white rounded-lg border shadow-sm p-4">
                  <h2 className="font-semibold mb-2">Ranked Findings ← response.llm.rankedFindings</h2>
                  <div className="space-y-2">
                    {output.llm.rankedFindings.map((f, i) => (
                      <div key={i} className="p-2 bg-gray-50 rounded border text-sm">
                        <div className="flex justify-between items-center mb-1">
                          <span>{f.label}</span>
                          <span className="text-xs text-gray-600">{(f.probability * 100).toFixed(1)}%</span>
                        </div>
                        <p className="text-xs text-gray-600">{f.rationale}</p>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="bg-white rounded-lg border shadow-sm p-4">
                  <h2 className="font-semibold mb-2">Possible Differentials ← response.llm.differentials</h2>
                  <div className="space-y-2">
                    {output.llm.differentials.map((d, i) => (
                      <div key={i} className="p-2 bg-gray-50 rounded border text-sm">
                        <div className="flex justify-between items-center mb-1">
                          <span>{d.condition}</span>
                          <span className="text-xs px-2 py-0.5 rounded bg-gray-200">{d.confidence}</span>
                        </div>
                        <p className="text-xs text-gray-600">{d.reason}</p>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="bg-white rounded-lg border shadow-sm p-4">
                  <h2 className="font-semibold mb-2">Recommended Next Steps ← response.llm.recommendedActions</h2>
                  <div className="space-y-2">
                    {output.llm.recommendedActions.map((a, i) => (
                      <div key={i} className="flex items-start gap-2 p-2 rounded text-sm">
                        <span className="text-xs px-2 py-0.5 rounded border bg-gray-50">{a.urgency}</span>
                        <span>{a.action}</span>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 text-sm text-amber-900">
                  ← response.llm.safetyNote: {output.llm.safetyNote}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
